[package]
name = "serde_test_suite_deps"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
publish = false

[workspace]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_derive_state = { path = "../../serde_derive" }
