[package]
name = "serde_test"
version = "1.0.21" # remember to update html_root_url
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>", "David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Token De/Serializer for testing De/Serialize implementations"
homepage = "https://serde.rs"
repository = "https://github.com/serde-rs/serde"
documentation = "https://docs.serde.rs/serde_test/"
keywords = ["serde", "serialization"]
readme = "README.md"
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]

[dependencies]
serde = { version = "1.0" }
serde_state = { version = "0.4.1", path = "../serde_state" }

[dev-dependencies]
serde = { version = "1.0", features = ["rc"] }
serde_derive = { version = "1.0" }
serde_derive_state = { version = "0.4.3", path = "../serde_derive" }

[badges]
travis-ci = { repository = "serde-rs/serde" }
