[package]
name = "serde_test_suite"
version = "0.0.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>", "David Tolnay <dtolnay@gmail.com>"]
publish = false

[features]
unstable = ["serde/unstable", "compiletest_rs"]

[dev-dependencies]
fnv = "1.0"
proc-macro2 = "0.4"
rustc-serialize = "0.3.16"
serde = { version = "1.0.0", features = ["rc"] }
serde_state = { path = "../serde_state", features = ["rc"] }
serde_derive = { version = "1", features = ["deserialize_in_place"] }
serde_derive_state = { path = "../serde_derive", features = ["deserialize_in_place"] }
serde_test = { path = "../serde_test" }

[dependencies]
compiletest_rs = { version = "0.3", optional = true }
