[package]
name = "serde_test_suite"
version = "0.0.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>", "David Tolnay <dtolnay@gmail.com>"]
publish = false

[features]
unstable = ["serde/unstable", "compiletest_rs"]

[dev-dependencies]
fnv = "1.0"
rustc-serialize = "0.3.16"
serde = "1.0.0"
serde_seed = { path = "../serde_seed" }
serde_derive = "1.0"
serde_derive_seed = { path = "../serde_derive" }
serde_test = { path = "../serde_test" }

[dependencies]
compiletest_rs = { version = "0.2", optional = true }
